### ISSUE TITLE
APK Download

### ISSUE THREAD

**Issue by IzzySoft** [chillibits/color-converter#267]
Could you make the APK available for download (e.g. attaching it to its corresponding release) for those without access to PlayStore? Or maybe bring your app to [F-Droid](https://f-droid.org/) so it becomes available without the need to register any account? Thanks in advance!

**Comment by marcauberer** [comment]
@IzzySoft Hi, the latest release has an apk file attached. Thanks for using Color Converter!

**Comment by IzzySoft** [comment]
Thanks! Did you also decide on a license (preferably a F/LOSS one approved by OSI/FSF, see e.g. the [SPDX license list](https://spdx.org/licenses/))? Currently I was unable to find any license pointed out here, which makes it "proprietary" aka "all rights reserved".

**Comment by IzzySoft** [comment]
@marcauberer any chance for a license being named? Apologies for the repeated ping, but I wasn't sure if my original one reached you…

**Comment by marcauberer** [comment]
Yes I got the message, but am not decided yet. I'm considering MIT license.

**Comment by IzzySoft** [comment]
Thanks! Then I'll wait patiently for your final decision. MIT sounds fine btw :smiley:

**Comment by IzzySoft** [comment]
Hm, looks like the decision is harder than I thought :speak_no_evil: :dash:

**Comment by IzzySoft** [comment]
Hm, still no license and the latest release again without APK – so it seems the two won't come and stay? That excludes those without access to Google's walled garden from using your app. With both available, I could include your app with [my repo](https://apt.izzysoft.de/fdroid) – but without I can't.
